##

prosubs:
 - ["file://localhost", ""]

replacements:
 - { regexp: \.(jpg|jpeg|gif|png)$, pattern: '<img src="{path}" width="{pixelWidth}" height="{pixelHeight}" alt="" />', type: image }
 - { regexp: \.css$, pattern: '<link rel="stylesheet" type="text/css" href="{path}" />', type: file }
 - { regexp: \.js$, pattern: '<script src="{path}" type="text/javascritp"></script>', type: file }
 - { regexp: \.(html?|php|pdf)$, pattern: '<a href="{path}"></a>', type: file }
